### PR TITLE
add EncodeConfig::max_frame_rate

### PR DESCRIPTION
**Pull request by astraw**

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Thanks!

Just with the previous one, could you just add a short `/// ...` line to the `pub` method explaining what the setting does so people get IDE hints?

**Comment by astraw** [comment]
Sure. I updated the PR.

**Comment by ralfbiedert** [comment]
Btw, do you want a new release? 

I was holding back with a new one since 1.64 would be the MSRV on `master`, but if there is demand I can just push another one for 1.63 right now.

**Comment by astraw** [comment]
Thanks! I am afraid the backtrace changes will not arrive until rust 1.65. I don't think pushing a new patch release that breaks compatibility with existing stable is a good idea. I have made PR #17 to address this. If you think this is OK to merge, then yes a new release would be great.

**Pull request merged**
